'use strict';
const $=id=>document.getElementById(id);
const token=location.hash.slice(1)||sessionStorage.getItem('jarvis-token')||'';
if(location.hash){sessionStorage.setItem('jarvis-token',token);history.replaceState(null,'',location.pathname);}
let state=null,configured=false,busy=false,imageData='',itemKind='',toastTimer,quitting=false,lastEvent='',page='home';
const titles={home:'VISÃO GERAL',chat:'CONVERSAR',projects:'PROJETOS',automations:'AUTOMAÇÕES',memory:'MEMÓRIA',integrations:'INTEGRAÇÕES',settings:'CONFIGURAÇÕES'};
const actionNames={open_url:'Abrir site',open_app:'Abrir aplicativo',save_note:'Salvar nota',add_reminder:'Criar lembrete',monitor_site:'Monitorar site'};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function toast(msg){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6500);}
async function api(path,method='GET',data){const res=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json','X-Jarvis-Token':token},body:data===undefined?undefined:JSON.stringify(data)});let out;try{out=await res.json();}catch{throw Error(res.status===401?'Sessão inválida. Feche esta janela e abra o JARVIS novamente.':'Não foi possível ler a resposta do aplicativo.');}if(!res.ok)throw Error(out.error||'Falha na operação.');return out;}
function guarded(fn){return async function(...args){try{await fn.apply(this,args);}catch(e){toast(e.message||'Ocorreu um erro.');}};}
function navigate(name){if(!titles[name])return;page=name;document.querySelectorAll('.page').forEach(n=>n.classList.toggle('hidden',n.id!=='page-'+name));document.querySelectorAll('#nav button').forEach(n=>n.classList.toggle('active',n.dataset.page===name));$('crumb').textContent=titles[name];if(name==='chat')$('prompt').focus();window.scrollTo(0,0);}
function count(kind){return (state.items||[]).filter(i=>i.kind===kind).length;}
async function refresh(initial=false){const out=await api('state');state=out.state;configured=out.configured;$('greeting').textContent=state.name||'Comandante';document.querySelector('.avatar').textContent=(state.name||'C').slice(0,1).toUpperCase();$('aiStatus').textContent=configured?'CHAVE CONFIGURADA':'IA NÃO CONECTADA';$('aiStatus').classList.toggle('amber',!configured);$('engineLabel').textContent=configured?'Chave configurada':'A configurar';$('engineLabel').className=configured?'cyan':'amber-text';$('coreState').textContent=configured?'READY FOR REQUEST':'READY TO CONNECT';$('platform').textContent=out.platform==='windows'?'Windows · 64 bits':'Ambiente de teste';$('projectCount').textContent=count('project');$('monitorCount').textContent=count('monitor');$('noteCount').textContent=count('note');$('reminderCount').textContent=(state.items||[]).filter(i=>i.kind==='reminder'&&!i.done).length;$('dataDir').textContent='Pasta de dados: '+out.dataDir;$('apiKey').placeholder=configured?'Chave salva • deixe vazio para manter':'Cole sua chave de API';if(initial){$('userName').value=state.name;$('model').value=state.model;$('memoryText').value=state.memory||'';renderMessages();}renderItems();renderActivity();renderIntegrations();const event=(state.events||[]).at(-1);if(event&&lastEvent&&event.time+event.text!==lastEvent&&event.text.startsWith('LEMBRETE:')){toast(event.text);if($('voiceReply').checked)speak(event.text);}if(event)lastEvent=event.time+event.text;}
function renderActivity(){const box=$('activity');box.replaceChildren();const events=(state.events||[]).slice(-4).reverse();if(!events.length){box.append(el('p','','Tudo pronto para começar. Configure a IA ou crie seu primeiro projeto.'));return;}for(const e of events){const row=el('div','activity-row');row.append(el('time','',new Date(e.time).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})),el('span','',e.text));box.append(row);}}
function renderItems(){for(const [kind,id] of [['project','projectsList'],['monitor','monitorsList'],['reminder','remindersList'],['note','notesList']]){const list=$(id);list.replaceChildren();const items=(state.items||[]).filter(i=>i.kind===kind);if(!items.length){list.append(el('div','empty',{'project':'Seu próximo projeto começa aqui. Clique em “Novo projeto”.','monitor':'Nenhum site monitorado. Adicione uma URL para começar.','reminder':'Sua agenda está livre. Adicione um lembrete.','note':'Guarde ideias, referências e informações úteis.'}[kind]));continue;}for(const item of items){const card=el('article','panel item-card');card.append(el('div','kind',{project:'WORKSPACE',monitor:'SITE MONITOR',reminder:'LEMBRETE',note:'MEMÓRIA'}[kind]),el('h3','',item.name));if(kind==='monitor'){card.append(el('span','badge'+(item.status&&!item.status.startsWith('HTTP 2')?' amber':''),item.status||'Aguardando primeira checagem'));card.append(el('p','',item.value));}else if(kind==='reminder'){card.append(el('p','',new Date(item.due).toLocaleString('pt-BR')),el('span','badge'+(item.done?'':' amber'),item.done?'CONCLUÍDO':'PENDENTE'));}else{card.append(el('p','',item.value||'Projeto sem link vinculado.'));}const actions=el('div','card-actions');if((kind==='project'||kind==='monitor')&&/^https?:\/\//i.test(item.value)){const link=el('a','','Abrir ↗');link.href=item.value;link.target='_blank';link.rel='noopener noreferrer';actions.append(link);}else actions.append(el('small','','Salvo neste computador'));const del=el('button','delete','Excluir');del.addEventListener('click',guarded(async()=>{if(!confirm('Excluir “'+item.name+'”?'))return;await api('items/'+item.id,'DELETE');await refresh();toast('Item excluído.');}));actions.append(del);card.append(actions);if(kind==='monitor'&&item.checked)card.append(el('small','', 'Última checagem: '+new Date(item.checked).toLocaleTimeString('pt-BR')));list.append(card);}}}
function addRichText(box,text){const parts=text.split(/```(?:[a-zA-Z0-9_+.-]+)?\n?/g);parts.forEach((part,i)=>{box.append(el(i%2?'pre':'span','',part));});}
function message(role,text){const box=el('div','message '+role);box.append(el('div','role',role==='user'?'VOCÊ':'JARVIS'));const body=el('div','text');addRichText(body,text);box.append(body);$('messages').append(box);$('messages').scrollTop=$('messages').scrollHeight;return box;}
function renderMessages(){const box=$('messages');box.replaceChildren();if(!(state.messages||[]).length){const welcome=el('div','welcome');welcome.append(el('div','symbol','◈'),el('h2','','Como posso ajudar?'),el('p','','Uma ideia, uma pergunta ou o seu próximo projeto.'));const suggestions=el('div','suggestions');for(const text of ['Me ajude a planejar um site','Abra a calculadora','Salve uma nota sobre meu projeto']){const b=el('button','',text);b.onclick=()=>{$('prompt').value=text;$('prompt').focus();};suggestions.append(b);}welcome.append(suggestions);box.append(welcome);}else for(const m of state.messages)message(m.role,m.content);}
function showActions(actions){for(const a of actions){const card=el('div','action-card');card.append(el('b','',actionNames[a.name]||a.name));const details=el('pre','',Object.entries(a.args).map(([k,v])=>k+': '+v).join('\n'));card.append(details);const approve=el('button','primary','Autorizar ação'),deny=el('button','outline','Recusar');const answer=async yes=>{approve.disabled=deny.disabled=true;try{const out=await api('action','POST',{id:a.id,approve:yes});card.append(el('p','',out.result));await refresh();message('assistant',out.result);}catch(e){card.append(el('p','error-message',e.message));}};approve.onclick=()=>answer(true);deny.onclick=()=>answer(false);card.append(approve,deny);$('messages').append(card);}$('messages').scrollTop=$('messages').scrollHeight;}
async function sendChat(e){e.preventDefault();if(busy)return;const text=$('prompt').value.trim();if(!text)return;if(!configured){toast('Configure sua chave de API para iniciar a conversa.');navigate('settings');return;}busy=true;$('send').disabled=true;document.querySelector('.welcome')?.remove();message('user',text+(imageData?'\n[Imagem anexada]':''));const pending=message('assistant','Processando sua solicitação…');pending.classList.add('pending');const payload={text,image:imageData,mode:$('mode').value};$('prompt').value='';try{const out=await api('chat','POST',payload);pending.remove();message('assistant',out.text);showActions(out.actions||[]);if($('voiceReply').checked)speak(out.text);clearImage();await refresh();}catch(err){pending.classList.remove('pending');pending.querySelector('.text').textContent=err.message;pending.querySelector('.text').classList.add('error-message');$('prompt').value=text;}finally{busy=false;$('send').disabled=false;$('prompt').focus();}}
function speak(text){if(!('speechSynthesis'in window)){toast('Leitura de voz indisponível neste navegador.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.slice(0,6000));u.lang='pt-BR';u.rate=1;const voice=speechSynthesis.getVoices().find(v=>v.lang==='pt-BR');if(voice)u.voice=voice;speechSynthesis.speak(u);}
function clearImage(){imageData='';$('attachment').replaceChildren();$('attachment').classList.add('hidden');$('imageInput').value='';}
function renderIntegrations(){const list=$('integrationCards');list.replaceChildren();for(const x of [['◈','OpenAI','Chat com ferramentas, análise de imagens e contexto pessoal.',configured?'CHAVE SALVA · TESTE ENVIANDO UMA MENSAGEM':'DISPONÍVEL · CONFIGURE A CHAVE',true],['◷','Rotinas locais','Lembretes e monitoramento HTTP de sites públicos.','DISPONÍVEL NESTA VERSÃO',true],['▦','Windows','Calculadora, Bloco de notas e Explorador de arquivos.','DISPONÍVEL NO WINDOWS',true],['⎇','GitHub & deploy','Repositórios, alterações de código, testes e publicação.','NÃO IMPLEMENTADO NESTA VERSÃO',false],['✉','E-mail & calendário','Mensagens, compromissos e planejamento conectado.','NÃO IMPLEMENTADO NESTA VERSÃO',false],['⌁','WhatsApp & dispositivos','Mensageria, casa conectada e controle de dispositivos.','NÃO IMPLEMENTADO NESTA VERSÃO',false]]){const card=el('article','panel item-card');card.append(el('div','integration-icon',x[0]),el('h3','',x[1]),el('p','',x[2]),el('div','integration-status',x[3]));if(x[1]==='OpenAI'){const b=el('button','outline','Configurar ↗');b.onclick=()=>navigate('settings');card.append(el('br'),b);}list.append(card);}}
function openCreate(kind){itemKind=kind;$('itemTitle').textContent={project:'Novo projeto',monitor:'Monitorar site',reminder:'Novo lembrete',note:'Nova nota'}[kind];$('itemForm').reset();$('valueLabel').classList.toggle('hidden',kind==='reminder');$('dueLabel').classList.toggle('hidden',kind!=='reminder');$('itemDue').required=kind==='reminder';$('itemValue').required=kind==='monitor';$('valueTitle').textContent=kind==='note'?'Conteúdo':kind==='project'?'URL do projeto (opcional)':'URL pública do site';$('itemValue').placeholder=kind==='note'?'Escreva sua nota…':'https://';$('itemDialog').showModal();$('itemName').focus();}
async function saveSettings(extra={}){return api('settings','POST',{name:$('userName').value,model:$('model').value,key:$('apiKey').value,memory:$('memoryText').value,...extra});}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>openCreate(b.dataset.create));document.querySelectorAll('[data-launch]').forEach(b=>b.onclick=guarded(async()=>{await api('launch','POST',{app:b.dataset.launch});toast('Comando enviado ao Windows.');}));
$('chatForm').addEventListener('submit',sendChat);$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('chatForm').requestSubmit();}});
$('clearChat').onclick=guarded(async()=>{if(busy){toast('Aguarde a resposta antes de limpar.');return;}if(!confirm('Apagar o histórico desta conversa? As notas serão mantidas.'))return;await api('chat','DELETE');await refresh();renderMessages();});
$('settingsForm').onsubmit=guarded(async e=>{e.preventDefault();await saveSettings();$('apiKey').value='';await refresh();toast('Configurações salvas. Envie uma mensagem para testar a conexão.');});
$('forgetKey').onclick=guarded(async()=>{if(!confirm('Remover a chave de API deste computador?'))return;await saveSettings({key:'',forgetKey:true});$('apiKey').value='';await refresh();toast('Chave removida.');});
$('saveMemory').onclick=guarded(async()=>{await api('settings','POST',{name:state.name,model:state.model,memory:$('memoryText').value});await refresh();toast('Memória salva.');});
$('itemForm').onsubmit=guarded(async e=>{e.preventDefault();const data={name:$('itemName').value.trim(),kind:itemKind,value:$('itemValue').value.trim(),due:itemKind==='reminder'?new Date($('itemDue').value).toISOString():''};await api('items','POST',data);$('itemDialog').close();await refresh();toast('Item salvo.');});$('closeDialog').onclick=()=>$('itemDialog').close();
$('checkSites').onclick=guarded(async()=>{const b=$('checkSites');b.disabled=true;b.textContent='Verificando…';try{await api('check','POST');await refresh();toast('Checagem concluída.');}finally{b.disabled=false;b.textContent='Verificar sites agora';}});
$('attach').onclick=()=>$('imageInput').click();$('imageInput').onchange=guarded(async()=>{const f=$('imageInput').files[0];if(!f)return;if(f.size>5*1024*1024)throw Error('Escolha uma imagem de até 5 MB.');if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('Use PNG, JPG ou WebP.');imageData=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Não foi possível ler a imagem.'));r.readAsDataURL(f);});const img=el('img');img.src=imageData;img.alt='Prévia da imagem selecionada';const b=el('button','icon-button','×');b.onclick=clearImage;$('attachment').replaceChildren(img,el('span','',f.name+' · será enviada à API com sua mensagem'),b);$('attachment').classList.remove('hidden');});
let recognition;const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
$('mic').onclick=()=>{if(!SpeechRecognition){toast('Ditado indisponível neste navegador. No Windows, use Win + H no campo da mensagem.');$('prompt').focus();return;}if(recognition){recognition.stop();return;}recognition=new SpeechRecognition();recognition.lang='pt-BR';recognition.interimResults=false;recognition.continuous=false;recognition.onresult=e=>{$('prompt').value+=($('prompt').value?' ':'')+e.results[0][0].transcript;$('prompt').focus();};recognition.onerror=e=>toast('Não foi possível ditar: '+e.error+'. Você pode usar Win + H.');recognition.onend=()=>{recognition=null;$('mic').classList.remove('listening');};try{recognition.start();$('mic').classList.add('listening');toast('Ouvindo. Fale sua mensagem.');}catch(e){recognition=null;toast('Microfone indisponível. Confira a permissão do navegador.');}};
$('stopVoice').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();};$('quit').onclick=guarded(async()=>{if(!confirm('Encerrar o JARVIS e parar os monitores locais?'))return;await api('quit','POST');quitting=true;toast('JARVIS encerrado. Você pode fechar esta janela.');document.querySelectorAll('button').forEach(b=>b.disabled=true);});
function clock(){$('clock').textContent=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});}clock();setInterval(clock,1000);
refresh(true).catch(e=>toast(e.message));setInterval(()=>{if(!quitting)refresh().catch(()=>{});},6000);